<%@ Page Language="C#" AutoEventWireup="true" CodeBehind="Gridview.aspx.cs" Inherits="DataBaseGridView.Gridview" %>

<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml">
<head runat="server">
    <title>Employee Records</title>
</head>
<body>
    <form id="form1" runat="server">
        <div style="margin-bottom: 20px;">
            <h2>Insert New Employee</h2>
            <table>
                <tr>
                    <td>Name:</td>
                    <td><asp:TextBox ID="txtName" runat="server" /></td>
                </tr>
                <tr>
                    <td>Designation:</td>
                    <td><asp:TextBox ID="txtDesignation" runat="server" /></td>
                </tr>
                <tr>
                    <td>Joining Date:</td>
                    <td><asp:TextBox ID="txtJoiningDate" runat="server" Placeholder="yyyy-mm-dd" /></td>
                </tr>
                <tr>
                    <td>Mobile No:</td>
                    <td><asp:TextBox ID="txtMobNo" runat="server" /></td>
                </tr>
                <tr>
                    <td>Gender:</td>
                    <td><asp:TextBox ID="txtGender" runat="server" /></td>
                </tr>
                <tr>
                    <td colspan="2">
                        <asp:Button ID="btnInsert" runat="server" Text="Insert" OnClick="btnInsert_Click" />
                    </td>
                </tr>
            </table>
        </div>

        <h2>Employee List</h2>
        <asp:GridView ID="GridView1" runat="server" AutoGenerateColumns="False" 
            DataKeyNames="EmpID" DataSourceID="SqlDataSource1" 
            AutoGenerateDeleteButton="True">
            <Columns>
                <asp:BoundField DataField="EmpID" HeaderText="EmpID" ReadOnly="True" />
                <asp:BoundField DataField="Name" HeaderText="Name" />
                <asp:BoundField DataField="Designation" HeaderText="Designation" />
                <asp:BoundField DataField="JoiningDate" HeaderText="Joining Date" />
                <asp:BoundField DataField="MobNo" HeaderText="Mobile No" />
                <asp:BoundField DataField="Gender" HeaderText="Gender" />
                <asp:CommandField ShowDeleteButton="True" />
            </Columns>
        </asp:GridView>

        <asp:SqlDataSource ID="SqlDataSource1" runat="server" 
            ConnectionString="<%$ ConnectionStrings:ConnectionString %>" 
            SelectCommand="SELECT * FROM [Table]" 
            DeleteCommand="DELETE FROM [Table] WHERE [EmpID] = @EmpID">
            <DeleteParameters>
                <asp:Parameter Name="EmpID" Type="Int32" />
            </DeleteParameters>
        </asp:SqlDataSource>
    </form>
</body>
</html>
